### ISSUE TITLE
在禁止右边刷新时，向左拖动的时候，K线图超出左边界时候会崩溃，请问怎么解决？

### ISSUE THREAD

**Issue by xiaoyudexiee** [wordplat/ikvStockChart#29]
崩溃日志：
Process: com.wordplat.InteractiveKLineView.example, PID: 2541
                                                                                         java.lang.ArrayIndexOutOfBoundsException
                                                                                             at android.graphics.Canvas.native_drawLines(Native Method)
                                                                                             at android.graphics.Canvas.drawLines(Canvas.java:1089)
                                                                                             at com.wordplat.ikvstockchart.drawing.MADrawing.onComputeOver(MADrawing.java:125)
                                                                                             at com.wordplat.ikvstockchart.render.KLineRender.renderDrawingList(KLineRender.java:324)
                                                                                             at com.wordplat.ikvstockchart.render.KLineRender.render(KLineRender.java:275)
                                                                                             at com.wordplat.ikvstockchart.InteractiveKLineView.onDraw(InteractiveKLineView.java:530)
                                                                                             at android.view.View.draw(View.java:17185)
                                                                                             at android.view.View.updateDisplayListIfDirty(View.java:16167)
                                                                                             at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
                                                                                             at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
                                                                                             at android.view.View.updateDisplayListIfDirty(View.java:16130)
                                                                                             at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
                                                                                             at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
                                                                                             at android.view.View.updateDisplayListIfDirty(View.java:16130)
                                                                                             at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
                                                                                             at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
                                                                                             at android.view.View.updateDisplayListIfDirty(View.java:16130)
                                                                                             at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
                                                                                             at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
                                                                                             at android.view.View.updateDisplayListIfDirty(View.java:16130)
                                                                                             at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
                                                                                             at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
                                                                                             at android.view.View.updateDisplayListIfDirty(View.java:16130)
                                                                                             at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
                                                                                             at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
                                                                                             at android.view.View.updateDisplayListIfDirty(View.java:16130)
                                                                                             at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
                                                                                             at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
                                                                                             at android.view.View.updateDisplayListIfDirty(View.java:16130)
                                                                                             at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:648)
                                                                                             at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:654)
                                                                                             at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:762)
                                                                                             at android.view.ViewRootImpl.draw(ViewRootImpl.java:2800)
                                                                                             at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2608)
                                                                                             at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2215)
                                                                                             at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
                                                                                             at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
                                                                                             at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                                                                                             at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                                             at android.view.Choreographer.doFrame(Choreographer.java:621)
                                                                                             at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                                                                             at android.os.Handler.handleCallback(Handler.java:751)
                                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                             at android.os.Looper.loop(Looper.java:154)
                                                                                             at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by wangyi793797714** [comment]
楼主解决了吗
